# Data Preparation Lab -- Module 2, Class 2

**Dataset:** Superstore Sales

In this lab you will:
1. Load and inspect data
2. Handle missing values
3. Remove duplicates
4. Convert data types
5. Create derived features

The first 3 tasks are pre-built. The rest are TODO for you.

---
## Setup: Load the Dataset

Option A: Upload from Kaggle (download from https://www.kaggle.com/datasets/vivek468/superstore-dataset-final)

Option B: Use the URL loader below.

In [43]:
import pandas as pd
import numpy as np

# Option A: Upload in Colab
# from google.colab import files
# uploaded = files.upload()  # upload your CSV
# df = pd.read_csv('SampleSuperstore.csv')

# Option B: Load from a public URL
# If the URL does not work, use Option A.
url = "https://raw.githubusercontent.com/leonism/sample-superstore/master/data/superstore.csv"

try:
    df = pd.read_csv(url, encoding='latin-1')
    print(f"Loaded from URL: {df.shape[0]} rows, {df.shape[1]} columns")
except Exception as e:
    print(f"URL failed ({e}). Use Option A: upload the CSV manually.")
    # Fallback: upload manually
    from google.colab import files
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(filename, encoding='latin-1')
    print(f"Loaded from upload: {df.shape[0]} rows, {df.shape[1]} columns")

# This code acts like a "Smart Mailman" that tries to grab your store data from the internet first.
# If the internet link is broken, it uses a backup plan that lets you pick the file from your own computer.
# It makes sure your information is ready in a digital table called 'df' so you can start cleaning it.

Loaded from URL: 10800 rows, 21 columns

In [44]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

# This code is like a "Special Delivery" bot that goes to a giant toy warehouse called Kaggle to find the newest box of store data.
# It downloads the box to a secret spot on your computer and then tells you exactly where it hid it so you can go find it.

Using Colab cache for faster access to the 'superstore-dataset-final' dataset.
Path to dataset files: /kaggle/input/superstore-dataset-final

---
## Task 1: Inspect the Data (pre-built)

Always look at your data before doing anything to it.

In [45]:
# First 5 rows
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [46]:
# Shape: rows x columns
print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")

# This code is like using a giant ruler to measure how big your table of data is.
# It tells you exactly how many rows and columns you have so you know how much information you're working with.

Shape: 10800 rows, 21 columns

In [47]:
# Data types and non-null counts
df.info()

# This code is like a health check-up for your data table.
# It tells you what kind of information is in each column (like numbers or names) and if there are any empty spots that need fixing.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10800 non-null  object
 1   Order ID       10800 non-null  object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9983 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   float64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(5), object(16)
memory usage: 1.7+ MB

In [48]:
# Summary statistics for numerical columns
df.describe()

# This code is like a "Magic Math Report" that looks at all the numbers in your box.
# It quickly tells you the average, the smallest number, and the biggest number so you can see how much things usually cost.

        Postal Code         Sales     Quantity     Discount       Profit
count   9983.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55245.233297    229.858001     3.789574     0.156203    28.656896
std    32038.715955    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    57103.000000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

---
## Task 2: Missing Values (pre-built)

Check which columns have missing values and how many.

In [49]:
# Count missing values per column
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    'missing_count': missing,
    'missing_pct': missing_pct
})

# Show only columns with missing values
missing_report[missing_report['missing_count'] > 0]

# This code is like a detective hunting for missing puzzle pieces in your big box of data.
# It counts every empty spot and shows you a list of only the parts that are broken so you know exactly what needs to be fixed.

               missing_count  missing_pct
Order Date               806         7.46
Ship Date                806         7.46
Ship Mode                806         7.46
Customer ID              806         7.46
Customer Name            806         7.46
Segment                  806         7.46
Country                  806         7.46
City                     806         7.46
State                    806         7.46
Postal Code              817         7.56
Region                   806         7.46
Product ID               806         7.46
Category                 806         7.46
Sub-Category             806         7.46
Product Name             806         7.46
Sales                    806         7.46
Quantity                 806         7.46
Discount                 806         7.46
Profit                   806         7.46

In [50]:
# Fill missing numerical values with median (robust to outliers)
numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        print(f"Filled {col} missing values with median: {median_val}")

# Fill missing categorical values with mode
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        mode_val = df[col].mode()[0]
        df[col].fillna(mode_val, inplace=True)
        print(f"Filled {col} missing values with mode: {mode_val}")

# Verify: no more missing values
print(f"\nTotal missing values remaining: {df.isnull().sum().sum()}")

# This code is like a "Fix-It Bot" that finds empty holes in your data and fills them in so the table is complete.
# It uses a "middle-sized" number to fix number holes and the most popular word to fix name holes.
# At the end, it double-checks to make sure every single gap is filled.

Filled Postal Code missing values with median: 57103.0
Filled Sales missing values with median: 54.489999999999995
Filled Quantity missing values with median: 3.0
Filled Discount missing values with median: 0.2
Filled Profit missing values with median: 8.6665
Filled Order Date missing values with mode: 9/5/2017
Filled Ship Date missing values with mode: 12/16/2016
Filled Ship Mode missing values with mode: Standard Class
Filled Customer ID missing values with mode: WB-21850
Filled Customer Name missing values with mode: William Brown
Filled Segment missing values with mode: Consumer
Filled Country missing values with mode: United States
Filled City missing values with mode: New York City
Filled State missing values with mode: California
Filled Region missing values with mode: West
Filled Product ID missing values with mode: OFF-PA-10001970
Filled Category missing values with mode: Office Supplies
Filled Sub-Category missing values with mode: Binders
Filled Product Name missing values with mode: Staple envelope

Total missing values remaining: 0

/tmp/ipykernel_3833/1316087364.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipykernel_3833/1316087364.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

---
## Task 3: Remove Duplicates (pre-built)

In [51]:
# Check for duplicates
n_duplicates = df.duplicated().sum()
print(f"Duplicate rows found: {n_duplicates}")

# Remove duplicates
if n_duplicates > 0:
    df = df.drop_duplicates()
    print(f"After removal: {df.shape[0]} rows remain")
else:
    print("No duplicates to remove.")

# This code is like a "Twin Detector" that hunts for identical copies of the same receipt.
# If it finds any, it keeps one and puts the extras in the recycling bin so you don't count the same sale twice.

Duplicate rows found: 504
After removal: 10296 rows remain

---
## Task 4: Convert Date Columns (TODO)

The `Order Date` and `Ship Date` columns are stored as strings. Convert them to proper datetime objects.

Hint: Use `pd.to_datetime()`. After conversion, verify with `.dtypes`.

In [52]:
# Check current types of date columns
print("Before conversion:")
for col in df.columns:
    if 'date' in col.lower() or 'Date' in col:
        print(f"  {col}: {df[col].dtype}")
        print(f"  Sample value: {df[col].iloc[0]}")

# This code is like a detective searching for any folder labeled 'Date' to see what's inside.
# It reports back what kind of information is in those folders and shows you a tiny sample so you can see if they look like real calendar dates or just plain words.

Before conversion:
  Order Date: object
  Sample value: 11/8/2017
  Ship Date: object
  Sample value: 11/11/2017

In [53]:
# TODO: Convert date columns to datetime
# Look at the column names printed above and convert them.
# The column names may vary depending on the dataset version.
#
# Example pattern:
# df['Column Name'] = pd.to_datetime(df['Column Name'])

# Your code here:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# This code is like teaching the computer how to read a calendar.
# It turns plain words into real dates so the computer knows exactly when things happened and can put them in the right order.

In [54]:
# TODO: Verify the conversion worked
# Print dtypes for the date columns to confirm they are datetime64

# Your code here:
print(df[['Order Date', 'Ship Date']].dtypes)

# This code is like checking your work after finishing a puzzle.
# It asks the computer to show you the labels on those columns one last time, just to be 100% sure it really understands they are dates now!

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

---
## Task 5: Derived Features (TODO)

Create customer-level summary features. These are the building blocks for customer segmentation (Activity 4).

You need to create:
- **total_spending**: Total sales per customer
- **order_frequency**: Number of orders per customer
- **avg_order_value**: Average sales amount per order per customer

Hint: Use `df.groupby('Customer ID')` (or whatever the customer ID column is named).

In [55]:
# First, identify the right column names
print("All columns:")
for col in df.columns:
    print(f"  {col}")

# This code is like reading the table of contents for your big book of data.
# It prints out the name of every single column so you can find the exact "labels" needed to build your summary reports.

All columns:
  Row ID
  Order ID
  Order Date
  Ship Date
  Ship Mode
  Customer ID
  Customer Name
  Segment
  Country
  City
  State
  Postal Code
  Region
  Product ID
  Category
  Sub-Category
  Product Name
  Sales
  Quantity
  Discount
  Profit

In [56]:
# TODO: Create total_spending per customer
# Hint: df.groupby('Customer ID')['Sales'].sum()
#
# Replace column names below with the actual names from your dataset.

# customer_spending = df.groupby('???')['???'].sum()
# customer_spending.name = 'total_spending'

# Your code here:
customer_spending = df.groupby('Customer ID')['Sales'].sum()
customer_spending.name = 'total_spending'

In [57]:
# TODO: Create order_frequency per customer
# Hint: Count the number of rows (orders) per customer.
# Use .groupby(...).size() or .groupby(...)['some_col'].count()

# Your code here:
order_freq = df.groupby('Customer ID').size()
order_freq.name = 'order_frequency'

In [58]:
# TODO: Create avg_order_value per customer
# Hint: Use .groupby(...)['Sales'].mean()

# Your code here:
avg_order = df.groupby('Customer ID')['Sales'].mean()
avg_order.name = 'avg_order_value'

In [59]:
# TODO: Combine all three into a single customer-level DataFrame
# Hint: Use pd.concat([series1, series2, series3], axis=1)
# or create them all at once with .groupby(...).agg(...)

# customer_summary = pd.concat([customer_spending, order_freq, avg_order], axis=1)
# customer_summary.columns = ['total_spending', 'order_frequency', 'avg_order_value']

# Your code here:
customer_summary = pd.concat([customer_spending, order_freq, avg_order], axis=1)

In [60]:
# TODO: Display the first 10 rows of your customer summary and .describe()

# Your code here:
print(customer_summary.head(10))
print(customer_summary.describe())

             total_spending  order_frequency  avg_order_value
Customer ID
AA-10315           5563.560               11       505.778182
AA-10375           1056.390               15        70.426000
AA-10480           1790.512               12       149.209333
AA-10645           5086.935               18       282.607500
AB-10015            886.156                6       147.692667
AB-10060           7755.620               18       430.867778
AB-10105          14473.571               20       723.678550
AB-10150            966.710               12        80.559167
AB-10165           1113.838               14        79.559857
AB-10255            914.532               14        65.323714
       total_spending  order_frequency  avg_order_value
count      793.000000       793.000000       793.000000
mean      2917.600051        12.983607       227.742345
std       2717.903575        13.137232       190.416146
min          4.833000         1.000000         2.416500
25%       1146.050000         8.000000       115.485500
50%       2256.394000        12.000000       183.924000
75%       3785.276000        16.000000       282.688947
max      25043.050000       339.000000      1751.292000

---
## Task 6: Save Cleaned Data (TODO)

Save the cleaned DataFrame to a new CSV file. Never overwrite the original.

In [61]:
# TODO: Save the cleaned main DataFrame
# df.to_csv('superstore_cleaned.csv', index=False)

# TODO: Save the customer summary DataFrame
# customer_summary.to_csv('customer_summary.csv')

# Your code here:
df.to_csv('superstore_cleaned.csv', index=False)
customer_summary.to_csv('customer_summary.csv')
print("Files saved successfully!")

Files saved successfully!

---
## Reflection

Answer these in a text cell or comments:

1. Why did we use median instead of mean for filling numerical missing values?
2. What is the difference between the row-level DataFrame (one row per order) and the customer-level summary? When would you use each?
3. If two rows have identical values in every column, are they always true duplicates? When might they not be?

1. Why use median instead of mean?
The median is used because it isn't easily swayed by "outliers," which are numbers that are much higher or lower than the rest. It provides a more "normal" middle value that accurately represents the data even if there are a few extreme values.

2. Row-level vs. Customer-level?
A row-level table shows every single receipt or action, while a customer-level table is a "report card" that summarizes everything one person did. You use row-level data to see daily details and customer-level data to see who your most loyal shoppers are.

3. Are identical rows always duplicates?
Not necessarily, because someone could have simply bought the exact same item at the same price and time. However, in many datasets, this is often an error where the same information was accidentally recorded twice.

***Assignment 2***

In [62]:
import pandas as pd
import os

# Assuming 'path' variable from kagglehub.dataset_download is available in the environment,
# or re-initialize it if this cell is run independently.
# For continuity, let's ensure 'path' and 'file_path' are defined if not already.
# If this cell is run after previous Kaggle download cells, 'file_path' should exist.

# Re-initialize path and file_path for robustness if running this cell in isolation
# This part can be removed if confident 'path' and 'file_path' are always available.
try:
    # Check if 'path' is already defined, if not, try to get it.
    if 'path' not in locals() and 'path' not in globals():
        import kagglehub
        path = kagglehub.dataset_download("vivek468/superstore-dataset-final")
    file_path = os.path.join(path, "Sample - Superstore.csv")
except NameError:
    # Fallback if path is not defined and cannot be re-downloaded easily, though this is less likely in Colab
    print("Warning: 'path' not found. Ensure Kaggle dataset is downloaded and 'path' is defined.")
    # If you intend to upload manually, uncomment the following lines and remove the above 'try-except' block:
    # from google.colab import files
    # uploaded = files.upload()
    # filename = list(uploaded.keys())[0]
    # file_path = filename

# Load the dataset using the correct file_path
df = pd.read_csv(file_path, encoding='windows-1252')

# Display the first 10 rows
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [63]:
# Check the shape of the dataset
print("Shape:", df.shape)

# See data types and non-null counts
df.info()

# Summary statistics of numerical columns
print(df.describe())

# Check for missing values
print(df.isnull().sum())

Shape: (9994, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
            Row ID   Postal Code         Sales     Quantity     Discount  \
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203
std    2885.163629  32063.693350    623.245101     2.225110     0.206452
min       1.000000   1040.000000      0.444000     1.000000     0.000000
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000

            Profit
count  9994.000000
mean     28.656896
std     234.260108
min   -6599.978000
25%       1.728750
50%       8.666500
75%      29.364000
max    8399.976000
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

I inspected the Superstore dataset structure to understand its format and quality. I checked the total number of rows and columns using the shape property, evaluated data types with the info method, and calculated basic statistics. Finally, I searched for missing values across all columns to prepare for data cleaning.

In [64]:
# Fill missing values in numerical columns with median (using Sales as an example)
if df['Sales'].isnull().sum() > 0:
    df['Sales'].fillna(df['Sales'].median(), inplace=True)

# Fill missing values in categorical columns with mode (using Ship Mode as an example)
if df['Ship Mode'].isnull().sum() > 0:
    df['Ship Mode'].fillna(df['Ship Mode'].mode()[0], inplace=True)

# Verify no missing values remain
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

I handled the missing values in the dataset to prevent issues during data analysis. Numerical missing data were filled using the median because it is robust against outliers, while categorical missing gaps were replaced with the mode. Afterward, I verified that the total count of remaining missing values is zero.

In [65]:
# Count duplicate rows
print("Duplicate rows before:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Verify shape after removal
print("Shape after removing duplicates:", df.shape)

Duplicate rows before: 0
Shape after removing duplicates: (9994, 21)

I scanned the dataset for identical rows that could skew our analytical results. Any identified duplicate rows were successfully dropped using the drop_duplicates method. This keeps our dataset clean, accurate, and ensures each transaction row represents a unique record.

In [66]:
# Convert date columns to proper datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Verify conversion
print(df.dtypes)

# Spot-check a few rows
df[['Order Date', 'Ship Date']].head()

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

  Order Date  Ship Date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18

The order and shipping dates were initially loaded as text strings, which limits time-based calculation. I converted both columns into proper datetime objects using the to_datetime function. I verified the change by displaying their data types and spot-checking sample values.

In [67]:
# Step 1: Calculate total spending per customer
total_spending = df.groupby('Customer ID')['Sales'].sum().reset_index()
total_spending.columns = ['Customer ID', 'total_spending']

# Step 2: Calculate order frequency (unique orders per customer)
order_freq = df.groupby('Customer ID')['Order ID'].nunique().reset_index()
order_freq.columns = ['Customer ID', 'order_frequency']

# Step 3: Calculate average order value
avg_order = df.groupby('Customer ID')['Sales'].mean().reset_index()
avg_order.columns = ['Customer ID', 'avg_order_value']

# Step 4: Merge all into a customer summary table
customer_summary = total_spending.merge(order_freq, on='Customer ID').merge(avg_order, on='Customer ID')

# Display the first 10 rows
print(customer_summary.head(10))

# Step 5: Save both cleaned DataFrames to CSV
df.to_csv('superstore_cleaned.csv', index=False)
customer_summary.to_csv('customer_summary.csv', index=False)
print("Files saved successfully!")

  Customer ID  total_spending  order_frequency  avg_order_value
0    AA-10315        5563.560                5       505.778182
1    AA-10375        1056.390                9        70.426000
2    AA-10480        1790.512                4       149.209333
3    AA-10645        5086.935                6       282.607500
4    AB-10015         886.156                3       147.692667
5    AB-10060        7755.620                8       430.867778
6    AB-10105       14473.571               10       723.678550
7    AB-10150         966.710                5        80.559167
8    AB-10165        1113.838                8        79.559857
9    AB-10255         914.532                9        65.323714
Files saved successfully!

I aggregated the transactional data to create a high-level customer summary profile. I computed the total spending, unique order frequency, and average order value for each unique customer ID. Finally, I merged these metrics into a single table and saved both the cleaned transaction data and customer summaries into new CSV files